/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as OauthLoginRouteImport } from './routes/oauth/login'
import { Route as ApiDocumentsChatRouteImport } from './routes/api/documents/chat'
import { Route as ApiRealtimeDashboardRouteImport } from './routes/api/realtime/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthLoginRoute = OauthLoginRouteImport.update({
  id: '/oauth/login',
  path: '/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsChatRoute = ApiDocumentsChatRouteImport.update({
  id: '/api/documents/chat',
  path: '/api/documents/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeDashboardRoute = ApiRealtimeDashboardRouteImport.update({
  id: '/api/realtime/dashboard',
  path: '/api/realtime/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/api/documents/chat': typeof ApiDocumentsChatRoute
  '/api/realtime/dashboard': typeof ApiRealtimeDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/api/documents/chat': typeof ApiDocumentsChatRoute
  '/api/realtime/dashboard': typeof ApiRealtimeDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/login': typeof OauthLoginRoute
  '/api/documents/chat': typeof ApiDocumentsChatRoute
  '/api/realtime/dashboard': typeof ApiRealtimeDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oauth/consent'
    | '/oauth/login'
    | '/api/documents/chat'
    | '/api/realtime/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth/consent'
    | '/oauth/login'
    | '/api/documents/chat'
    | '/api/realtime/dashboard'
  id:
    | '__root__'
    | '/'
    | '/oauth/consent'
    | '/oauth/login'
    | '/api/documents/chat'
    | '/api/realtime/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthLoginRoute: typeof OauthLoginRoute
  ApiDocumentsChatRoute: typeof ApiDocumentsChatRoute
  ApiRealtimeDashboardRoute: typeof ApiRealtimeDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/login': {
      id: '/oauth/login'
      path: '/oauth/login'
      fullPath: '/oauth/login'
      preLoaderRoute: typeof OauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/chat': {
      id: '/api/documents/chat'
      path: '/api/documents/chat'
      fullPath: '/api/documents/chat'
      preLoaderRoute: typeof ApiDocumentsChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime/dashboard': {
      id: '/api/realtime/dashboard'
      path: '/api/realtime/dashboard'
      fullPath: '/api/realtime/dashboard'
      preLoaderRoute: typeof ApiRealtimeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthLoginRoute: OauthLoginRoute,
  ApiDocumentsChatRoute: ApiDocumentsChatRoute,
  ApiRealtimeDashboardRoute: ApiRealtimeDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
